name: Bug Report
description: Report a bug or issue with LocalAI Chat
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running LocalAI Chat?
      options:
        - Development (npm run dev)
        - Production (npm start)
        - Docker Container
        - Docker Compose
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: ai_service
    attributes:
      label: AI Service
      description: Which AI service are you connecting to?
      options:
        - LM Studio
        - Ollama
        - LocalAI
        - Other OpenAI-compatible API
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Mobile (iOS)
        - Mobile (Android)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Error Messages
      description: If applicable, add console logs or error messages
      placeholder: Paste any relevant logs or error messages here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...