name: Feature Request
description: Suggest a new feature or enhancement for LocalAI Chat
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Improvement
        - New AI Service Integration
        - Performance Enhancement
        - Mobile/PWA Feature
        - Developer Experience
        - Security/Privacy
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: List any alternatives you've considered...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots or examples about the feature request
      placeholder: Any additional information, mockups or examples...